### ISSUE TITLE
Ed25519 to X25519 conversion

### ISSUE THREAD

**Issue by kdenhartog** [StableLib/stablelib#11]
I'm not seeing the functionality to do a conversion from an Ed25519 key to an X25519 key, but I did see that you wrote [this package](https://github.com/dchest/ed2curve-js) which is capable of doing this. Would you be interested if I made a PR to add this functionality into stablelib? Also, could the return object of these functions be used with the X25519 packages?

**Comment by dchest** [comment]
Yes, thank you! I think it would make sense to just add conversion functions to https://github.com/StableLib/stablelib/blob/master/packages/ed25519/ed25519.ts to reuse existing arithmetic functions instead of copying them  (I did it as a separate package from TweetNaCl.js to keep it a true port of TweetNaCl without adding anything, but here we can go wild :-)

**Comment by dchest** [comment]
Implemented (https://github.com/StableLib/stablelib/commit/e39714a078083161ef4761326507eecdc704f4ac) and published.
